### ISSUE TITLE
Inability to configure request timeout leads to DoS / resource leak

### ISSUE THREAD

**Issue by Shnatsel** [mardiros/cabot#7]
Cabot currently does not allow specifying a timeout for the entire request (i.e. until the request body is finished transferring), which means an established connection will keep going indefinitely if the remote host keeps replying.

This is fine for the simple use cases, like a user downloading something interactively, but enables denial-of-service attacks in automated scenarios: if the remote host keeps transferring data at a really low speed, e.g. several bytes per second, the connection will be open indefinitely. This makes it easy for an attacker who can submit URLs to the server to cause denial of service through some kind of resource exhaustion - running out of RAM, networking ports, etc. More details on the attack scenario can be found [here](https://github.com/sbstp/attohttpc/issues/35#issuecomment-572239063).

**Comment by Shnatsel** [comment]
[Read timeout is also not set](https://github.com/mardiros/cabot/blob/24629157d03e9880ef9d3a06de32d49295d29ff9/src/http.rs#L380), so the connection will be open indefinitely even if the remote host goes away. This is a serious reliability issue, see [here](https://medium.com/@nate510/don-t-use-go-s-default-http-client-4804cb19f779) for more info.

**Comment by SamWilsn** [comment]
I haven't dug into the internals of async-std, but I believe one of the useful properties of Rust's futures is that when a future is dropped, the underlying operation is cancelled.

So you could implement a timeout by selecting on a read operation and on a timer. Once the timer pops, the read is cancelled.

Again, not 100% sure, but I think that's the theory.

**Comment by mardiros** [comment]
> [Read timeout is also not set](https://github.com/mardiros/cabot/blob/24629157d03e9880ef9d3a06de32d49295d29ff9/src/http.rs#L380), so the connection will be open indefinitely even if the remote host goes away. 

I completly forget to fix that while switching to async-std :worried:  (there is not set_read_timeout on TCPStream in async-std)

**Comment by mardiros** [comment]
Fix in #12

**Comment by Shnatsel** [comment]
Thanks! However, I don't think this is entirely fixed. There is still no way to specify a timeout for the entire request. 

If the remote host keeps transferring data at a really low speed, e.g. several bytes per second, the connection will be open indefinitely. This makes it easy for an attacker who can submit URLs to the server to cause denial of service through some kind of resource exhaustion - running out of RAM, networking ports, etc. More details on the attack scenario can be found [here](https://github.com/sbstp/attohttpc/issues/35#issuecomment-572239063).

**Comment by mardiros** [comment]
You are right, I miss the global timeout
