### ISSUE TITLE
Allow supplying custom logger

### ISSUE THREAD

**Issue by Shnatsel** [mardiros/cabot#8]
Right now cabot has a hard dependency on [pretty_env_logger](https://crates.io/crates/pretty_env_logger) which pulls in a great deal of code through its dependencies, with large parts of it being unsafe. This increases compilation time and creates unnecessary attack surface.

Please provide an option to use a custom log adapter and avoid the dependency on `pretty_env_logger`.

**Comment by mardiros** [comment]
Fixed in #11
